sudo: required
services:
  - docker

before_install:
  - docker build -t leannelyons/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leannelyons/react-test npm test

after_success:
  - docker build -t leannelyons/multi-client ./client
  - docker build -t leannelyons/multi-nginx ./nginx
  - docker build -t leannelyons/multi-server ./server
  - docker build -t leannelyons/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push leannelyons/multi-client
  - docker push leannelyons/multi-nginx
  - docker push leannelyons/multi-server
  - docker push leannelyons/multi-worker

# Required if you want to deploy to AWS
    #deploy:
    #  provider: elasticbeanstalk
    #  region: us-west-1
    #  app: multi-docker
    #  env: MultiDocker-env
    #  bucket_name: elasticbeanstalk-us-west-1-306476627547
    #  bucket_path: docker-multi
    #  on:
    #    branch: master
    #  access_key_id: $AWS_ACCESS_KEY
    #  secret_access_key: $AWS_SECRET_KEY
